# Shell variables
# Generated by 'wal'
wallpaper='/home/thadeu/.config/wpg/wallpapers/gotham-rain.jpg'

# Special
background='#000000'
foreground='#ffdcb5'
cursor='#ffdcb5'

# Colors
color0='#202020'
color1='#df1902'
color2='#3a7475'
color3='#df6601'
color4='#1c575b'
color5='#b4060a'
color6='#253749'
color7='#cab399'
color8='#4e4e4e'
color9='#ff3902'
color10='#40a1a3'
color11='#ff8601'
color12='#1d8188'
color13='#e20106'
color14='#2d4b5f'
color15='#ffdcb5'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
