#!/bin/sh
### Created by ilsenatorov
THEME_DIR=$HOME/.config/desktop/colors
cd $THEME_DIR

list_themes() {
    find $THEME_DIR -name '*.json' \
    |sed 's/^.*\///g;s/\.json$//g'
}
if [ -z "$@" ]; then
	list_themes
else
    THEME=$@
    if [ -n "${THEME}" ]; then
        wal --theme ${THEME_DIR}/${THEME}.json > /dev/null
        ~/.config/desktop/scripts/recolor ~/.cache/wal/colors.json
        $HOME/.config/desktop/setup.sh > /dev/null
    fi
	list_themes
fi
cd - > /dev/null
