#!/bin/sh
### Created by ilsenatorov
### Change WALLPAPERDIR to the directory where you store wallpapers

WALLPAPERDIR=$HOME/Imagens/Wallpaper

if [ -z "$@" ]; then
	get_themes() {
	    ls $WALLPAPERDIR
	}
	echo current; get_themes
else
    THEMES="$@"
    if [ x"current" = x"${THEMES}" ]
    then
	exit 0
        # wal -i `cat ~/.cache/wal/wal` > /dev/null #Allows you to just stay with current theme
    elif [ -n "${THEMES}" ]
    then
        # colorz schemer2 wal haishoku colorthief
        wal -t --backend schemer2 -i $WALLPAPERDIR/${THEMES} > /dev/null
        ~/.config/desktop/scripts/theme.sh > /dev/null
        ~/.config/desktop/scripts/recolor ~/.cache/wal/colors.json
        $HOME/.config/desktop/setup.sh > /dev/null
    fi
fi
