#!/bin/bash
export SCRIPTS=$HOME/.config/desktop/scripts
export ROFI="rofi -config $HOME/.config/desktop/rofi/config -theme $HOME/.cache/desktop/rofi-theme.rasi"
export APPS="$HOME/.config/desktop/rofi/apps"
action="$1"
shift;

. $HOME/.config/desktop/inc/colors.sh

input() {
	$ROFI -dmenu -lines 0 -p "$@"
}

rofi_windows() {
    $ROFI -show window -modi window,windowcd -window-match-fields title,name -window-format "{n:12} · {t}{w:2}"
}

rofi_settings() {
	if [[ "$1" == "" ]]; then
		$0 settings "$($0 settings --list | $ROFI -dmenu -p "Conf")"
		exit
	fi

	declare -A O
    export O
    for i in ${SCRIPTS}/settings/* ; do
        O["$(basename "$i" | sed -e 's/_/ /g; s/\b\w/\U&/g')"]="$i"
    done

	OPTION="$*"
	set +x
	if [[ "$1" == "--list" ]] ; then
		for i in "${!O[@]}"; do
			echo $i
		done
	else
		if [[ "${O["$OPTION"]}" != "" ]]; then
			exec bash -c "${O["$OPTION"]}"
		fi
	fi
}

rofi_wm_menu() {
	wallpaper=wallpaper:$APPS/wallpaper
	theme=theme:$APPS/theme
	$ROFI -sidebar-mode true \
		-show theme \
		-matching regex \
		-modi window,$wallpaper,$theme
}

rofi_run() {
	$ROFI -show drun -modi drun,ssh,window,run
}

rofi_todo() {
	$ROFI -sidebar-mode true \
		-show notes \
		-modi notes:$APPS/notes
}

rofi_calc() {
    $ROFI -show calc -modi calc
}

rofi_cheatsheets() {
    cd $HOME/git/cheatsheets/md
    file="$(\
        find . -name '*md'\
        | sed 's/^\.\///g' \
        | $ROFI -dmenu -l 10 \
        )"

    if [[ "$file" == "edit" ]]
        then x-terminal-emulator -e editor ./ ; exit; fi

    if [[ -z "$file" ]]
        then exit; fi

     [[ -n $TERM ]] \
     && x-terminal-emulator -e bat --decorations never \
        --theme ansi-dark \
        --paging always \
        "$file"
}

rename_current_window() {
#	window=$(xwininfo | grep 'xwininfo: Window id' | awk '{print $4}')
	window=$(xdotool getactivewindow)
    echo $window >> /tmp/x
	name=$(input 'Window title')
	xdotool set_window --name "${name}" "${window}"
}

case "$action" in

 "rename_workspace") i3-msg rename workspace to "$( input 'Workspace name')";;
 #"rename_window")    i3-msg title_format "$(input 'Window title')";;
 "rename_window")    rename_current_window $@;;
 "mark_add")         i3-msg mark "$(input "Add mark")";;
 "mark_focus")       i3-msg "[con_mark=\"$(input "Go to mark")\"] focus";;
 "wm_menu")          rofi_wm_menu ;;
 "todo")             rofi_todo ;;
 "theme")            wpg --noreload ;;
 "settings")         rofi_settings $@ ;;
 "calc")             rofi_calc;;
 "windows")          rofi_windows;;
 "run")              rofi_run $@;;
 "cheatsheets")      rofi_cheatsheets $@;;
esac
